### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [interlegis/sapl#2297]
Hello @interlegis
I designed a logo for your repository. I represented the Legislativo concept with a hammer. ( Also, The hammer represents the letter P.)  What do you think the logo? Please share your ideas with me. I will wait for feedback. Best regards.

![sapl](https://user-images.githubusercontent.com/36298335/46819928-a230f380-cd8d-11e8-84ce-bfe6972d215e.jpg)

**Comment by edwardoliveira** [comment]
Thanks for the contribution. I think the logo is pretty nice, but SAPL is a legislative support system for municipal deputies and alike, so I don't think a hammer is the good visual cue. Something along the lines of a book would be more suitable, imo. SAPL is a brazilian system so I think playing with blue/green/yellow/white colors Finally, another font could be chosen, so that the "L" could have the horizontal dash, but I am not a font expert by any means, so my opinion can be biased here.

Best regards
